apiVersion: v1
kind: Service
metadata:
  name: eginsoftui
  labels:
    app: eginsoftui
spec:
  type: NodePort
  selector:
    app: eginsoftui
  ports:
    - port: 5005
      nodePort: 30011
      protocol: TCP
      targetPort: 5005
